### ISSUE TITLE
Latest Version?

### ISSUE THREAD

**Issue by SamGoody** [denemo/denemo#2]
I am on a Mac (10.13.6).
Denemo 2.2.0 does not load for me. 
Even after letting it load overnight, it hangs when I open it.

I tried cloning the repo (and in this way also getting the last few hundred commits) , but how do I build it on a Mac? 

Is it possible to build for the Mac?
Is there a cask with something newer than 2.2?

**Comment by davidlrichmond** [comment]
Some progress now on building for the Mac....see http://denemo.org/hacking-sources/.

**Comment by azmeuk** [comment]
Thank you but this repository is just a mirror. The repository is hosted at https://savannah.gnu.org/git/?group=denemo
